server:
  port: 8088
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password: password

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@${DB_PORT_1521_TCP_ADDR:192.168.2.190}:${DB_PORT_1521_TCP_PORT:1522}/xe
#    username: stages_order
#    password: stages_order1688
#    initial-size: 1
#    min-idle: 3
#    max-active: 20
#    max-wait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 30000
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    platform: oracle

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        format_sql: true    
logging:
  level:
    com.sj.stages: debug
    org.apache.http: debug


spring:
  datasource.url: jdbc:mysql://localhost:3306/test
  datasource.username: root
  datasource.password: 123456
  datasource.driverClassName: com.mysql.jdbc.Driver
  jpa.database: MYSQL

  datasource.tomcat.max-idle: 10
  datasource.tomcat.max-wait: 10000
  datasource.tomcat.min-idle: 5
  datasource.tomcat.initial-size: 5
  datasource.tomcat.validation-query: SELECT 1
  datasource.tomcat.test-on-borrow: false
  datasource.tomcat.test-while-idle: true
  datasource.tomcat.time-between-eviction-runs-millis: 18800
  datasource.tomcat.jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)

## application.properties
## Server settings (ServerProperties)
#server.port=8080
#server.address=127.0.0.1
##server.sessionTimeout=30
#server.contextPath=/test

## Tomcat specifics
##server.tomcat.accessLogEnabled=false
#server.tomcat.protocolHeader=x-forwarded-proto
#server.tomcat.remoteIpHeader=x-forwarded-for
#server.tomcat.basedir=
#server.tomcat.backgroundProcessorDelay=

## REDIS (RedisProperties)
## Redis数据库索引（默认为0)
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=127.0.0.1
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0

    
  